default: &default
  adapter: mysql2
  username: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: eventmoo_development

test:
  <<: *default
  database: eventmoo_test

production:
  <<: *default
  database: eventmoo
